# Track configuration
boards:
  - id: master
    segments:
      - id: seg1
        address: 0x00
      - id: seg2
        address: 0x01
      - id: seg3
        address: 0x02
      - id: seg4
        address: 0x03
      - id: seg5
        address: 0x04
      - id: seg6
        address: 0x05
      - id: seg7
        address: 0x06
      - id: seg8
        address: 0x07
      - id: seg9
        address: 0x08
      - id: seg10
        address: 0x09
      - id: seg11
        address: 0x0A
      - id: seg12
        address: 0x0B
      - id: seg13
        address: 0x0C
      - id: seg14
        address: 0x0D
      - id: seg15
        address: 0x0E
      - id: seg16
        address: 0x0F
      - id: seg17
        address: 0x20
      - id: seg18
        address: 0x21
      - id: seg19
        address: 0x22
      - id: seg20
        address: 0x23
      - id: seg21
        address: 0x24
      - id: seg22
        address: 0x25
      - id: seg23
        address: 0x26
      - id: seg24
        address: 0x10
      - id: seg25
        address: 0x11
      - id: seg26
        address: 0x12
      - id: seg27
        address: 0x13
      - id: seg28
        address: 0x27
      - id: seg29
        address: 0x28
      - id: seg30
        address: 0x1D
      - id: seg31
        address: 0x1E
      - id: seg32
        address: 0x1F
      - id: seg33
        address: 0x14
      - id: seg34
        address: 0x15
      - id: seg35
        address: 0x16
      - id: seg36
        address: 0x17
      - id: seg37
        address: 0x18
      - id: seg38
        address: 0x19
      - id: seg39
        address: 0x1A
      - id: seg40
        address: 0x1B
      - id: seg41
        address: 0x1C